### ISSUE TITLE
Improve test coverage on your handlers

### ISSUE THREAD

**Issue by jsms90** [FAC10/week5-globetown-news-ammp#73]
You're not testing your serveNews or serveTravel handlers. Since this is the bulk of what your app does, this is a really good thing to focus on next

https://codecov.io/gh/FAC10/week5-globetown-news-ammp/src/master/src/handlers.js

**Comment by akinsho** [comment]
We will add tests to handle news and travel

**Comment by PiotrBerebecki** [comment]
@jsms90, thanks, we've added more tests for our handlers
